export const Food: any[] =[
  {
    id: 1,
    name: "Cow Milk",
    translated: "حليب بقرة",
    calories: 0.63,
    carbs: 0.046,
    fats: 0.036,
    protein: 0.031,
    suger: 0,
    quantity: 1,
    measure: "millimeter",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 2,
    name: "egg",
    translated: "بيضة",
    calories: 68,
    carbs: 0.5,
    fats: 4.7,
    protein: 5.5,
    suger: 0.5,
    quantity: 1,
    measure: "poiled egg meduim",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 3,
    name: "oat",
    translated: "شوفان نباتة",
    calories: 3.85,
    carbs: 0.66,
    fats: 0.024,
    protein: 0.25,
    suger: 0.165,
    quantity: 1,
    measure: "gm",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 4,
    name: "green beans",
    translated: "فاصوليا خضراء",
    calories: 0.101,
    carbs: 0.19,
    fats: 0.016,
    protein: 0.074,
    suger: 0.017,
    quantity: 1,
    measure: "gm",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 5,
    name: "potato",
    translated: "البطاطس",
    calories: 0.743,
    carbs: 0.176,
    fats: 0.002,
    protein: 0.02,
    suger: 0.007,
    quantity: 1,
    measure: "gm",
    servingQuantity: 173,
    servingMeasure: "gm/item"
  },
  {
    id: 6,
    name: "carrots",
    translated: "جزر",
    calories: 0.41,
    carbs: 0.0958,
    fats: 0.0042,
    protein: 0.0093,
    suger: 0.0474,
    quantity: 1,
    measure: "gm",
    servingQuantity: 46,
    servingMeasure: "gm/item"
  },
  {
    id: 7,
    name: "Yogurt",
    translated: "زبادي",
    calories: 0.928,
    carbs: 0.038,
    fats: 0.046,
    protein: 0.084,
    suger: 0.038,
    quantity: 1,
    measure: "gm",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 8,
    name: "granola",
    translated: "جرنولة",
    calories: 4.41,
    carbs: 0.68,
    fats: 0.13,
    protein: 0.095,
    suger: 0.18,
    quantity: 1,
    measure: "gm",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 9,
    name: "apple",
    translated: "تفاحة",
    calories: 0.52,
    carbs: 0.1381,
    fats: 0.0017,
    protein: 0.0026,
    suger: 0.1039,
    quantity: 1,
    measure: "gm",
    servingQuantity: 182,
    servingMeasure: "gm/item"
  },
  {
    id: 10,
    name: "banana",
    translated: "موز",
    calories: 0.89,
    carbs: 0.2284,
    fats: 0.0033,
    protein: 0.0109,
    suger: 0.1223,
    quantity: 1,
    measure: "gm",
    servingQuantity: 118,
    servingMeasure: "gm/item"
  },
  {
    id: 11,
    name: "dates",
    translated: "بلح",
    calories: 2.82,
    carbs: 0.7473,
    fats: 0.0042,
    protein: 0.024,
    suger: 0.6345,
    quantity: 1,
    measure: "gm",
    servingQuantity: 7.1,
    servingMeasure: "gm/item"
  },
  {
    id: 12,
    name: "Chicken Thigh",
    translated: "فخذ الدجاج",
    calories: 2.138,
    carbs: 0.001,
    fats: 0.138,
    protein: 0.238,
    suger: 0,
    quantity: 1,
    measure: "gm",
    servingQuantity: 0,
    servingMeasure: "gm/item"
  },
  {
    id: 13,
    name: "Chicken Breast",
    translated: "صدر دجاج",
    calories: 1.95,
    carbs: 0,
    fats: 0.0772,
    protein: 0.2955,
    suger: 0,
    quantity: 1,
    measure: "gm",
    servingQuantity: 0,
    servingMeasure: "gm/item"
  },
  {
    id: 14,
    name: "Chicken wing",
    translated: "جناح دجاجة",
    calories: 2.88,
    carbs: 0,
    fats: 0.193,
    protein: 0.2664,
    suger: 0,
    quantity: 1,
    measure: "gm",
    servingQuantity: 21,
    servingMeasure: "gm/item"
  },
  {
    id: 15,
    name: "meat",
    translated: "لحمة",
    calories: 2.87,
    carbs: 0,
    fats: 0.1929,
    protein: 0.2641,
    suger: 0,
    quantity: 1,
    measure: "gm",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 16,
    name: "tomato",
    translated: "طماطم",
    calories: 0.18,
    carbs: 0.0389,
    fats: 0.002,
    protein: 0.0088,
    suger: 0.0263,
    quantity: 1,
    measure: "gm",
    servingQuantity: 123,
    servingMeasure: "gm/item"
  },
  {
    id: 17,
    name: "Whey Protein",
    translated: "بروتين مصل اللبن",
    calories: 3.9,
    carbs: 0.1,
    fats: 0.03,
    protein: 0.8,
    suger: 0,
    quantity: 1,
    measure: "gm",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 18,
    name: "Beef Chops",
    translated: "ريش لحم بقري",
    calories: 1.4,
    carbs: 0,
    fats: 0.067,
    protein: 0.198,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 19,
    name: "Beef Shoulder",
    translated: "كتف لحم بقري",
    calories: 2.127,
    carbs: 0,
    fats: 0.146,
    protein: 0.206,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 20,
    name: "Beef Liver",
    translated: "لحم كبد البقر",
    calories: 1.194,
    carbs: 0,
    fats: 0.04,
    protein: 0.207,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 21,
    name: "Black Cardamom",
    translated: "الهيل الأسود",
    calories: 2.706,
    carbs: 0.525,
    fats: 0.028,
    protein: 0.067,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 22,
    name: "Black Grapes",
    translated: "العنب الأسود",
    calories: 0.607,
    carbs: 0.132,
    fats: 0.003,
    protein: 0.008,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 23,
    name: "Black Pepper",
    translated: "فلفل اسود",
    calories: 2.175,
    carbs: 0.362,
    fats: 0.027,
    protein: 0.101,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 24,
    name: "Blueberry",
    translated: "توت",
    calories: 0.57,
    carbs: 0.145,
    fats: 0.003,
    protein: 0.007,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 25,
    name: "Brinjal",
    translated: "برينجال",
    calories: 0.253,
    carbs: 0.035,
    fats: 0.003,
    protein: 0.015,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 26,
    name: "Buffalo Milk",
    translated: "لحم الجاموس",
    calories: 1.073,
    carbs: 0.084,
    fats: 0.066,
    protein: 0.037,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 27,
    name: "Butter",
    translated: "سمنة",
    calories: 9,
    carbs: 0,
    fats: 1,
    protein: 0,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 28,
    name: "Cabbage",
    translated: "كرنب",
    calories: 0.179,
    carbs: 0.024,
    fats: 0.001,
    protein: 0.016,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 29,
    name: "Calf Heart",
    translated: "قلب العجل",
    calories: 1.098,
    carbs: 0,
    fats: 0.038,
    protein: 0.188,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 30,
    name: "Capsicum Green",
    translated: "الفليفلة الخضراء",
    calories: 0.163,
    carbs: 0.018,
    fats: 0.003,
    protein: 0.011,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 31,
    name: "Capsicum Red",
    translated: "الفليفلة الحمراء",
    calories: 0.198,
    carbs: 0.021,
    fats: 0.005,
    protein: 0.015,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 32,
    name: "Capsicum Yellow",
    translated: "الفليفلة الصفراء",
    calories: 0.186,
    carbs: 0.02,
    fats: 0.004,
    protein: 0.014,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 33,
    name: "Carrot Orange",
    translated: "جزر برتقال",
    calories: 0.332,
    carbs: 0.056,
    fats: 0.005,
    protein: 0.01,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 34,
    name: "Carrot Red",
    translated: "جزر أحمر",
    calories: 0.382,
    carbs: 0.067,
    fats: 0.005,
    protein: 0.01,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 35,
    name: "Cashewnuts",
    translated: "الكاجو",
    calories: 5.826,
    carbs: 0.255,
    fats: 0.452,
    protein: 0.188,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 36,
    name: "Cauliflower",
    translated: "قرنبيط",
    calories: 0.229,
    carbs: 0.02,
    fats: 0.004,
    protein: 0.022,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 37,
    name: "Cheddar Cheese",
    translated: "جبنة الشيدر",
    calories: 4.03,
    carbs: 0.013,
    fats: 0.331,
    protein: 0.249,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 38,
    name: "Cheese Slice",
    translated: "قطعة جبن",
    calories: 62,
    carbs: 0.3,
    fats: 5,
    protein: 4,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 39,
    name: "Cherries",
    translated: "الكرز",
    calories: 0.598,
    carbs: 0.119,
    fats: 0.005,
    protein: 0.015,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 40,
    name: "Chicken Breast",
    translated: "صدر دجاج",
    calories: 1.684,
    carbs: 0,
    fats: 0.09,
    protein: 0.218,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 41,
    name: "Chicken Leg",
    translated: "فخذ دجاجة",
    calories: 3.84,
    carbs: 0,
    fats: 0.126,
    protein: 0.194,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 42,
    name: "Chicken Liver",
    translated: "كبدة دجاج",
    calories: 1.239,
    carbs: 0,
    fats: 0.041,
    protein: 0.216,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 43,
    name: "Chicken Thigh",
    translated: "فخذ الدجاج",
    calories: 2,
    carbs: 0,
    fats: 0.142,
    protein: 0.182,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 44,
    name: "Chicken Wings",
    translated: "أجنحة دجاج",
    calories: 1.931,
    carbs: 0,
    fats: 0.138,
    protein: 0.174,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 45,
    name: "Cream Cheese",
    translated: "جبنة الكريمة",
    calories: 3.5,
    carbs: 0.055,
    fats: 0.344,
    protein: 0.062,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 46,
    name: "Cucumber Green",
    translated: "خيار أخضر",
    calories: 0.196,
    carbs: 0.035,
    fats: 0.002,
    protein: 0.007,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 47,
    name: "Dates",
    translated: "بلح",
    calories: 3.202,
    carbs: 0.749,
    fats: 0.004,
    protein: 0.025,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 48,
    name: "Duck Meat",
    translated: "لحم البط",
    calories: 1.309,
    carbs: 0,
    fats: 0.06,
    protein: 0.191,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 49,
    name: "Egg",
    translated: "بيضة",
    calories: 60.705,
    carbs: 0,
    fats: 4.14,
    protein: 5.985,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 50,
    name: "Egg White",
    translated: "بياض البيضة",
    calories: 15.645,
    carbs: 0,
    fats: 0.035,
    protein: 4,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 51,
    name: "Egg Yolk",
    translated: "صفار البيض",
    calories: 55,
    carbs: 0.6,
    fats: 4.5,
    protein: 2.7,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 52,
    name: "Fig",
    translated: "تين",
    calories: 0.815,
    carbs: 0.163,
    fats: 0.004,
    protein: 0.02,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 53,
    name: "Fresh Coconut",
    translated: "جوز الهند الطازج",
    calories: 4.089,
    carbs: 0.063,
    fats: 0.414,
    protein: 0.038,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 54,
    name: "Fresh Peas",
    translated: "بازلاء طازجة",
    calories: 0.813,
    carbs: 0.119,
    fats: 0.001,
    protein: 0.073,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 55,
    name: "Garlic Big Clove",
    translated: "ثوم فص كبير",
    calories: 1.238,
    carbs: 0.219,
    fats: 0.002,
    protein: 0.069,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 56,
    name: "Garlic Small Clove",
    translated: "فص ثوم صغير",
    calories: 1.228,
    carbs: 0.218,
    fats: 0.001,
    protein: 0.007,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 57,
    name: "Greek Yogurt",
    translated: "زبادي يوناني",
    calories: 1.2,
    carbs: 0.064,
    fats: 0.08,
    protein: 0.05,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 58,
    name: "Green Apple",
    translated: "تفاحة خضراء",
    calories: 0.511,
    carbs: 0.107,
    fats: 0.005,
    protein: 0.005,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 59,
    name: "Green Grapes",
    translated: "العنب الأخضر",
    calories: 0.561,
    carbs: 0.122,
    fats: 0.003,
    protein: 0.008,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 60,
    name: "Green Pumpkin",
    translated: "اليقطين الأخضر",
    calories: 0.246,
    carbs: 0.042,
    fats: 0.002,
    protein: 0.009,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 61,
    name: "Green Tomato",
    translated: "طماطم خضراء",
    calories: 0.208,
    carbs: 0.032,
    fats: 0.003,
    protein: 0.011,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 62,
    name: "Green Zucchini",
    translated: "الكوسة الخضراء",
    calories: 0.201,
    carbs: 0.023,
    fats: 0.005,
    protein: 0.011,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 63,
    name: "Guava",
    translated: "جوافة",
    calories: 0.466,
    carbs: 0.051,
    fats: 0.003,
    protein: 0.012,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 64,
    name: "Jam",
    translated: "مربى",
    calories: 3.166,
    carbs: 0.833,
    fats: 0,
    protein: 0,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 65,
    name: "Mozzarella Cheese",
    translated: "جبنة موتزاريلا",
    calories: 2.6,
    carbs: 0.04,
    fats: 0.17,
    protein: 0.228,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 66,
    name: "Mushroom",
    translated: "فطر",
    calories: 0.277,
    carbs: 0.02,
    fats: 0.004,
    protein: 0.037,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 67,
    name: "Onion",
    translated: "بصلة",
    calories: 0.48,
    carbs: 0.096,
    fats: 0.002,
    protein: 0.015,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 68,
    name: "Pineapple",
    translated: "أناناس",
    calories: 0.43,
    carbs: 0.094,
    fats: 0.002,
    protein: 0.005,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 69,
    name: "Raisins Dried Black",
    translated: "الزبيب الأسود المجفف",
    calories: 3.056,
    carbs: 0.713,
    fats: 0.004,
    protein: 0.026,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 70,
    name: "Raisins Dried Golden",
    translated: "الزبيب المجفف ذهبي",
    calories: 2.966,
    carbs: 0.688,
    fats: 0.004,
    protein: 0.028,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 71,
    name: "Rye",
    translated: "الذرة",
    calories: 3.38,
    carbs: 0.75,
    fats: 0.01,
    protein: 0.01,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 72,
    name: "Spaghetti",
    translated: "معكرونة",
    calories: 3.5,
    carbs: 0.71,
    fats: 0.012,
    protein: 0.12,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 73,
    name: "Strawberry",
    translated: "الفراولة",
    calories: 0.32,
    carbs: 0.077,
    fats: 0.003,
    protein: 0.007,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 74,
    name: "Sugar",
    translated: "سكر",
    calories: 4,
    carbs: 1,
    fats: 0,
    protein: 0,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 75,
    name: "Sugarcane Juice",
    translated: "عصير قصب السكر",
    calories: 0.578,
    carbs: 0.131,
    fats: 0.004,
    protein: 0.002,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 76,
    name: "Sunflower Oil",
    translated: "زيت عباد الشمس",
    calories: 9,
    carbs: 0,
    fats: 1,
    protein: 0,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 77,
    name: "Sunflower Seeds",
    translated: "بذور زهرة عباد الشمس",
    calories: 5.82,
    carbs: 0.241,
    fats: 0.498,
    protein: 0.193,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 78,
    name: "Sweet Biscuit",
    translated: "بسكويت حلو",
    calories: 4.739,
    carbs: 0.652,
    fats: 0.217,
    protein: 0.086,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 79,
    name: "Sweet Corn",
    translated: "ذرة حلوه",
    calories: 0.86,
    carbs: 0.187,
    fats: 0.013,
    protein: 0.003,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 80,
    name: "Sweet Potato",
    translated: "بطاطا حلوة",
    calories: 1.09,
    carbs: 0.168,
    fats: 0.043,
    protein: 0.013,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 81,
    name: "Beans",
    translated: "فول",
    calories: 140,
    carbs: 9,
    fats: 5,
    protein: 10,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 82,
    name: "Burger",
    translated: "برجر",
    calories: 25.7,
    carbs: 3.231,
    fats: 0.922,
    protein: 1.162,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 83,
    name: "Kaiser",
    translated: "كايزر",
    calories: 27.9,
    carbs: 5.455,
    fats: 0.17,
    protein: 1.077,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 84,
    name: "Falafel",
    translated: "فلافل",
    calories: 3.33,
    carbs: 0.3184,
    fats: 0.178,
    protein: 0.1331,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 85,
    name: "Bread Egyption",
    translated: "خبز مصري",
    calories: 270,
    carbs: 0,
    fats: 0,
    protein: 0,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "none"
  },
  {
    id: 86,
    name: "fish",
    translated: "سمكة",
    calories: 1.12,
    carbs: 0,
    fats: 0.0122,
    protein: 0.233,
    suger: 0,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 170,
    servingMeasure: "gm/item"
  },
  {
    id: 87,
    name: "mango",
    translated: "مانجو",
    calories: 0.65,
    carbs: 0.17,
    fats: 0.0027,
    protein: 0.0051,
    suger: 0.148,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 336,
    servingMeasure: "gm/item"
  },
  {
    id: 88,
    name: "rice",
    translated: "ارز",
    calories: 1.29,
    carbs: 0.279,
    fats: 0.0028,
    protein: 0.0266,
    suger: 0.0005,
    quantity: 1,
    measure: "gram (g)",
    servingQuantity: 0,
    servingMeasure: "gm/item"
  },
]
